config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'

  resources :reports

  get 'pdf/:id' => 'reports#pdf', :as => :pdf

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'csv'


  def index





  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def new
    @report = Report.new
  end

  def create


    require 'csv'

    uploaded_io = params[:report][:file]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end


    params[:report][:file] = uploaded_io.original_filename

    @report = Report.new(allowed_params)
    if @report.save
      flash[:notice] = 'Información agregada correctamente'


      CSV.foreach( Rails.root.join('public', 'uploads', @report.file) ) do |row|


        data = Record.new

        data.fecha = row[0]


        if row[1] == 'ANSWERED'
          data.estado = 1
        else
          data.estado = 0
        end

        data.report_id = @report.id

        data.save



      end



      redirect_to edit_report_path(@report.id)
    else
      render 'new'
    end


  end

  def edit



    @totalLlamadas = Record.where(:report_id => params[:id])
    @llamadasContestadas = Record.where(:report_id => params[:id], :estado => 1)
    @llamadasNoContestadas = Record.where(:report_id => params[:id], :estado => 0)

    puts @llamadasContestadas


    @report = Report.find(params[:id])
  end


  def update


    @report = Report.find(params[:id])

    if @report.update_attributes(allowed_params)
      flash[:notice] = 'Información actualizada correctamente'
      redirect_to reports_path
    else
      render 'new'
    end

  end


  def pdf
    @totalLlamadas = Record.where(:report_id => params[:id])
    @llamadasContestadas = Record.where(:report_id => params[:id], :estado => 1)
    @llamadasNoContestadas = Record.where(:report_id => params[:id], :estado => 0)

    puts @llamadasContestadas


    @report = Report.find(params[:id])



    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => 'Reporte '+@report.nombre,
               :orientation => 'Landscape',
               #:disposition                    => 'attachment',
               :font_name          => 'Arial',
               :margin => {:top                => 0,                     # default 10 (mm)
                           :bottom             => 0,
                           :left               => 0,
                           :right              => 0}
      end
    end



  end


  private
  def allowed_params
    params.require(:report).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Reportes</title>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
  <%= stylesheet_link_tag  'font-icons/entypo/css/entypo',
                           'bootstrap',
                           'neon-core',
                           'neon-theme',
                           'neon-forms',
                           'custom'
  %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body class="page-body">
    <div class="page-container">
      <%= render 'includes/menu' %>

      <div class="main-content">
        <%= yield %>
      </div>
</div>





    <%=  javascript_include_tag 'gsap/main-gsap.js',
                                'joinable',
                                'resizeable',
                                'neon-custom'

    %>



</body>
</html>

app/views/reports/create.html.erb
<h1>Reports#create</h1>
<p>Find me in app/views/reports/create.html.erb</p>

app/views/reports/index.html.erb
<h3>Reportes generados</h3>

<p>
  <a href="<%= new_report_path %>" class="btn btn-primary">
    <i class="entypo-plus"></i>
    Agregar Reporte
  </a>
</p>


<table class="table table-bordered table-striped datatable" id="table-2">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Fecha</th>

    <th>Actions</th>
  </tr>
  </thead>
  <tbody>


  <% @reports.each do |report| %>
  <tr>

    <td><%= report.nombre %></td>
    <td>7.2</td>

    <td>
      <a href="<%=  edit_report_path(report.id) %>" class="btn btn-default btn-sm btn-icon icon-left">
        <i class="entypo-pencil"></i>
        Editar
      </a>
      <a href="<%= pdf_path(report.id) %>" class="btn btn-info btn-sm btn-icon icon-left">
        <i class="entypo-info"></i>
        Generar PDF
      </a>
      <a href="#" class="btn btn-danger btn-sm btn-icon icon-left">
        <i class="entypo-cancel"></i>
        Eliminar
      </a>

    </td>
  </tr>
  <% end %>

  </tbody>
</table>

app/views/reports/new.html.erb
<%= form_for @report, :url => reports_path, :method=>'post',  multipart: true do |f|  %>
    <h2>Agregar nuevo reporte</h2>
    <div class="form-group">

        <%= f.label :nombre, 'Nombre' %>
        <%= f.text_field :nombre, :class =>'form-control'  %>

    </div>


    <div class="form-group">

    <%= f.file_field :file %>

    </div>



    <%= f.submit 'Guardar', :class=> 'btn btn-info ' %>
    <%=  link_to 'Cancelar', reports_path, :class=>'btn btn-warning' %>

<% end %>

app/views/reports/pdf.html.erb
<!doctype html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>

    <table>
      <tr>
        <%= wicked_pdf_image_tag 'logo.png'  %>
      </tr>
    </table>



</body>
</html>